
name: Alerta no Discord

on: [push] # O gatilho: toda vez que alguém der push no código

jobs:
  comunicacao-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar Mensagem
        uses: appleboy/discord-action@master
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            🚀 **Novo Push Detectado!**
            **Repositório:** ${{ github.repository }}
            **Autor:** ${{ github.actor }}
            **Mensagem:** ${{ github.event.head_commit.message }}
            Veja as alterações aqui: ${{ github.event.compare }}
