name: Discord Notification

on: [push, pull_request] # Define os eventos que disparam o alerta

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Discord Message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }} # Opcional se usar a URL completa
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }} # Opcional se usar a URL completa
          args: 'O projeto ${{ github.repository }} recebeu um novo push!'

