
- name: Discord Notification
  uses: Ilshidur/action-discord@master
  with:
    args: "O build falhou!"
  env:
    DISCORD_WEBHOOK_ID: ${{ secrets.DISCORD_WEBHOOK_ID }}
    DISCORD_WEBHOOK_TOKEN: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}

